### ISSUE TITLE
Virtual Fabric Support?

### ISSUE THREAD

**Issue by storage-mon** [openiomon/fos2graphite#1]
Hi, 
are virtual fabrics supported? I have installed the software, but the requests to the NameServer fail. There is also no VF-ID passed with the restapi call, so I wonder if virtual fabric is supported at all? Maybe I just have a configuration error? It would be great if I could get some help.

**Comment by munokar** [comment]
Hi,
currently there is no vF support...
It is on the list of planed features but due to a missing environment with vF active it will take some time.

**Comment by munokar** [comment]
Hi,
vFID Support has been added.
This will work unser the assumption that all logical switches in a virtual fabric are having the same vFID.

**Comment by munokar** [comment]
Hi,
do you have the loglevel set to debug to get some additional messages?
can you please paste the full line from the log?

**Comment by storage-mon** [comment]
Hi,

below you can find logfiles. loglevel is set to debug. 

2021/10/11 08:29:33 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Fabric TestA cannot be found of configuration file /opt/fos2graphite/conf/fos2graphite.conf ! Please check configuration file and add fabric information! 
2021/10/11 08:30:28 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Registering service for TestA 
2021/10/11 08:30:28 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Servicefile: /etc/systemd/system/fos2graphite-TestA.service has been created! 
2021/10/11 08:30:28 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Reloading systemctl daemon... 
2021/10/11 08:30:28 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Reload was done successful! 
2021/10/11 08:30:47 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to enable service for fabric TestA... 
2021/10/11 08:31:01 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Failed to enable service for fabric TestA! Please investigate! 
2021/10/11 08:31:07 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to enable service for fabric TestA... 
2021/10/11 08:31:07 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service enableed for fabric TestA! 
2021/10/11 08:32:47 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to start service for fabric TestA... 
2021/10/11 08:32:47 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service started for fabric TestA! 
2021/10/11 08:33:09 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > There is not service registered for Virtual_Fabric_102! Please register service using fos2graphite -register Virtual_Fabric_102 
2021/10/11 08:33:38 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Registering service for Virtual_Fabric_102 
2021/10/11 08:33:38 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Servicefile: /etc/systemd/system/fos2graphite-Virtual_Fabric_102.service has been created! 
2021/10/11 08:33:38 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Reloading systemctl daemon... 
2021/10/11 08:33:38 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Reload was done successful! 
2021/10/11 08:38:14 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to disable service for fabric TestA... 
2021/10/11 08:38:14 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service disableed for fabric TestA! 
2021/10/11 08:38:14 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to disable service for fabric Virtual_Fabric_102... 
2021/10/11 08:38:14 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service disableed for fabric Virtual_Fabric_102! 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for ALL 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for TestA 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:293) main::servicestatus > Execute: systemctl status fos2graphite-TestA with result:  
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > fos2graphite-TestA.service - FOS2GRAPHITE Service for TestA 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Loaded: loaded (/etc/systemd/system/fos2graphite-TestA.service; disabled; vendor preset: disabled) 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Active: active (running) since Mon 2021-10-11 08:32:47 CEST; 16min ago 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >      Docs: http://www.openiomon.org 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  Main PID: 128293 (fos2graphite-wo) 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Status: "Running reporters..." 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    CGroup: /system.slice/fos2graphite-TestA.service 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >            └─128293 /usr/bin/perl /opt/fos2graphite/bin/fos2graphite-worker.pl -conf /opt/fos2graphite/conf/fos2graphite.conf -fabric TestA 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Starting FOS2GRAPHITE Service for TestA... 
2021/10/11 08:49:10 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Started FOS2GRAPHITE Service for TestA. 
2021/10/11 08:49:49 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to enable service for fabric TestA... 
2021/10/11 08:49:49 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:322) main::service > Running system command: systemctl enable fos2graphite-TestA > /dev/null 2>&1 
2021/10/11 08:49:49 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service enableed for fabric TestA! 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for ALL 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for TestA 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:293) main::servicestatus > Execute: systemctl status fos2graphite-TestA with result:  
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > fos2graphite-TestA.service - FOS2GRAPHITE Service for TestA 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Loaded: loaded (/etc/systemd/system/fos2graphite-TestA.service; enabled; vendor preset: disabled) 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Active: active (running) since Mon 2021-10-11 08:32:47 CEST; 17min ago 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >      Docs: http://www.openiomon.org 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  Main PID: 128293 (fos2graphite-wo) 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Status: "Running reporters..." 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    CGroup: /system.slice/fos2graphite-TestA.service 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >            ├─ 55202 /usr/bin/perl /opt/fos2graphite/bin/fos2graphite-worker.pl -conf /opt/fos2graphite/conf/fos2graphite.conf -fabric TestA 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >            └─128293 /usr/bin/perl /opt/fos2graphite/bin/fos2graphite-worker.pl -conf /opt/fos2graphite/conf/fos2graphite.conf -fabric TestA 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Starting FOS2GRAPHITE Service for TestA... 
2021/10/11 08:49:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Started FOS2GRAPHITE Service for TestA. 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for ALL 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:281) main::servicestatus > Query service status for TestA 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:293) main::servicestatus > Execute: systemctl status fos2graphite-TestA with result:  
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > fos2graphite-TestA.service - FOS2GRAPHITE Service for TestA 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Loaded: loaded (/etc/systemd/system/fos2graphite-TestA.service; enabled; vendor preset: disabled) 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Active: active (running) since Mon 2021-10-11 08:32:47 CEST; 17min ago 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >      Docs: http://www.openiomon.org 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  Main PID: 128293 (fos2graphite-wo) 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    Status: "Running reporters..." 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >    CGroup: /system.slice/fos2graphite-TestA.service 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >            └─128293 /usr/bin/perl /opt/fos2graphite/bin/fos2graphite-worker.pl -conf /opt/fos2graphite/conf/fos2graphite.conf -fabric TestA 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus >  
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Starting FOS2GRAPHITE Service for TestA... 
2021/10/11 08:50:00 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:300) main::servicestatus > Oct 11 08:32:47 server01 systemd[1]: Started FOS2GRAPHITE Service for TestA. 
2021/10/11 08:51:35 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to restart service for fabric TestA... 
2021/10/11 08:51:35 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:322) main::service > Running system command: systemctl restart fos2graphite-TestA > /dev/null 2>&1 
2021/10/11 08:51:35 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service restarted for fabric TestA! 
2021/10/11 08:52:49 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to stop service for fabric TestA... 
2021/10/11 08:52:49 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:322) main::service > Running system command: systemctl stop fos2graphite-TestA > /dev/null 2>&1 
2021/10/11 08:52:49 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service stoped for fabric TestA! 
2021/10/11 08:52:54 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Trying to disable service for fabric TestA... 
2021/10/11 08:52:54 [DEBUG] (/opt/fos2graphite/bin/fos2graphite.pl:322) main::service > Running system command: systemctl disable fos2graphite-TestA > /dev/null 2>&1 
2021/10/11 08:52:55 [INFO] (/opt/fos2graphite/bin/fos2graphite.pl:56) main::console > Service disableed for fabric TestA! 

logfile for the fabric:
2021/10/11 08:32:49 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:366) main::getFabricSwitches > Discovered switch TA_Test1_Default ("ipadress") as member of fabric TestA and will use DNS-name: TA_Test1 
2021/10/11 08:32:49 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:367) main::getFabricSwitches > Will use TA_Test1 for Switch: TA_Test1_Default 
2021/10/11 08:33:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:33:00 
2021/10/11 08:33:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 128295 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:33:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:34:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:34:00 
2021/10/11 08:34:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 128335 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:34:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:35:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:35:00 
2021/10/11 08:35:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 128431 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:35:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:36:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:36:00 
2021/10/11 08:36:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 129755 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:36:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:37:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:37:00 
2021/10/11 08:37:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 6833 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:37:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:38:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:38:00 
2021/10/11 08:38:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 14267 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:38:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:39:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:39:00 
2021/10/11 08:39:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 16708 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:39:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:40:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:40:00 
2021/10/11 08:40:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 16813 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:40:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:41:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:41:00 
2021/10/11 08:41:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 18142 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:41:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:42:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:42:00 
2021/10/11 08:42:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 25660 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:42:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:43:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:43:00 
2021/10/11 08:43:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 33163 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:43:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:44:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:44:00 
2021/10/11 08:44:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 35932 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:44:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:45:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:45:00 
2021/10/11 08:45:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 35992 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:45:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:46:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:46:00 
2021/10/11 08:46:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 37320 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:46:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:47:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:47:00 
2021/10/11 08:47:00 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 44747 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:47:00 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:48:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:48:00 
2021/10/11 08:48:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 52045 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:48:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:49:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:49:00 
2021/10/11 08:49:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 55113 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:49:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:50:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:50:00 
2021/10/11 08:50:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 55202 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:50:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:51:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:51:00 
2021/10/11 08:51:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 56461 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:51:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default 
2021/10/11 08:51:35 [DEBUG] (/opt/fos2graphite/bin/fos2graphite-worker.pl:290) main::restLogin > Logging in to "ipadress" with user: restapi 
2021/10/11 08:51:35 [DEBUG] (/opt/fos2graphite/bin/fos2graphite-worker.pl:296) main::restLogin > URL for login: https://"ipadress"/rest/login 
2021/10/11 08:51:36 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:366) main::getFabricSwitches > Discovered switch TA_Test1_Default ("ipadress") as member of fabric TestA and will use DNS-name: TA_Test1 
2021/10/11 08:51:36 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:367) main::getFabricSwitches > Will use TA_Test1 for Switch: TA_Test1_Default 
2021/10/11 08:51:36 [DEBUG] (/opt/fos2graphite/bin/fos2graphite-worker.pl:321) main::restLogout > Logging out from "ipadress" by removing token: Custom_Basic cmVzdGFwaTp4eHg6M2U2MDA4NGM2OWRjMDJlZGZkZDVmNTA5NGMxMWMxZTZmZmM3MGEzMTRiY2Q3ZGUxMWMwMjYxY2JiZDA5NWFiYQ== 
2021/10/11 08:52:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:52:00 
2021/10/11 08:52:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:907) main::checkreporter > Looks like PID: 67160 for switch TA_Test1_Default is not running! It ended with returncode 111 
2021/10/11 08:52:01 [ERROR] (/opt/fos2graphite/bin/fos2graphite-worker.pl:908) main::checkreporter > Restarting for Switch TA_Test1_Default

**Comment by munokar** [comment]
Hi,

if it dying right after:

`2021/10/11 08:52:00 [INFO] (/opt/fos2graphite/bin/fos2graphite-worker.pl:853) main::reportmetrics > Collecting new set of data for TestA - TA_Test1_Default at 10/11/2021 08:52:00`

it is very likely that it can't open a socket to the graphite backend for communication.
Can you please verify the configuration in the `/opt/fos2graphite/conf/fos2graphite.conf`:

`[graphite]`
`graphite_host = 127.0.0.1`
`graphite_port = 2003`

Is you graphite backend installed on the same host? Is it using port 2003 for accepting metrics in plaintext-format?

**Comment by mamoep** [comment]
vF support was added with v0.1.6, logging for graphite socket init will be included in upcoming v0.2.0 release.
