### ISSUE TITLE
Cannot connect to the graphite server

### ISSUE THREAD

**Issue by ToMo999** [openiomon/fos2graphite#9]
Hi, maybe someone has a hint for me. 
I have fos2graphite up and running

> /opt/fos2graphite/bin/fos2graphite-worker.pl:1057) main::initservice > Service is initialized...
> /opt/fos2graphite/bin/fos2graphite-worker.pl:1074) main::servicestatus > Service message has been sent: Discovering fabric...
> /opt/fos2graphite/bin/fos2graphite-worker.pl:516) main::getFabricSwitches > Login to seed switch Fabric_1 / 1.2.3.4

And a [docker-graphite-statsd](https://github.com/graphite-project/docker-graphite-statsd/tree/master) on the other side. 

connection to carbon with ncat is working

> nc -v 1.1.2.2 2003
> Ncat: Version 7.92 ( https://nmap.org/ncat )
> Ncat: Connected to 1.1.2.2:2003.

But in the log from fos2graphite I see:

> /opt/fos2graphite/bin/fos2graphite-worker.pl:1037) main::initsocket > Cannot connect to the graphite server Connection refused

**Comment by mamoep** [comment]
Did you set this in the fos2graphite.conf?

[graphite]
graphite_host = 1.1.2.2
graphite_port = 2003

**Comment by ToMo999** [comment]
Yes. conf-file is correct and I also set this as -conf with fos2graphite.pl.

**Comment by mamoep** [comment]
You can set `loglevel = DEBUG` to get details for the connection.

**Comment by ToMo999** [comment]
The log-level is on DEBUG already. But in the log/fos2graphite_Fabric_1.log I can not see any verbose information about the connection to the graphite server.

> 2024/03/05 11:24:41 [INFO] (PID: 3632737 /opt/fos2graphite/bin/fos2graphite-worker.pl:1057) main::initservice > Service is initialized...
> 2024/03/05 11:24:41 [DEBUG] (PID: 3632737 /opt/fos2graphite/bin/fos2graphite-worker.pl:516) main::getFabricSwitches > Login to seed switch Fabric_1 / 1.2.3.4
> 2024/03/05 11:24:41 [FATAL] (PID: 3632737 /opt/fos2graphite/bin/fos2graphite-worker.pl:1037) main::initsocket > Cannot connect to the graphite server Connection refused
> 2024/03/05 11:24:41 [INFO] (PID: 3632737 /usr/local/share/perl5/Log/Log4perl/Logger.pm:866) Log::Log4perl::Logger::and_die > Received shutdown / kill signal for process 3632737 from systemd or logdie!

**Comment by munokar** [comment]
Are you running fos2graphite on the same system as carbon?
From the log it looks like "something" is preventing fos2graphite-worker.pl from connecting to the port.
Did you try to run fos2graphite manually as root or using the systemd server as user openionmon?

**Comment by ToMo999** [comment]
I run fos2graphite as root (./fos2graphite-worker.pl -conf ../conf/fos2graphite.conf -fabric Fabric_1 - correct?) and as openiomion over the systemd. 

/etc/systemd/system/fos2graphite-Fabric_1.service
[Service]
User=openiomon
Group=openiomon

**Comment by mamoep** [comment]
Both running methods give the same result? Anything visible in the syslog (I am thinking SElinux)?

**Comment by ToMo999** [comment]
I can't see anything. 
Only that the service is started and immediately stopped.

Mar  6 14:19:43 server1 audisp-syslog[953]: node=server1 type=SERVICE_START msg=audit(1709731183.479:201411): pid=1 uid=0 auid=4294967211 ses=4294967211 subj=system_u:system_r:init_t:s0 msg='unit=fos2graphite-Fabric_1 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' UID="root" AUID="unset"

Mar  6 14:19:43 server1 systemd[1]: fos2graphite-Fabric_1.service: Succeeded.Mar  6 14:19:43 server1 audisp-syslog[953]: node=server1 type=SERVICE_STOP msg=audit(1709731183.485:201412): pid=1 uid=0 auid=4294967211 ses=4294967211 subj=system_u:system_r:init_t:s0 msg='unit=fos2graphite-Fabric_1 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success' UID="root" AUID="unset"

**Comment by ToMo999** [comment]
It's a RHEL 8 server. 
your skript work. I see connections with tcpdump to 1.1.2.2

**Comment by mamoep** [comment]
Hmm then maybe the parsing of the config file is not working correctly and it is connection to the wrong host/port. Please edit the fos2graphite-worker.pl and add this line to initsocket function before line 1037 (the `$log->logdie` part).

`print "HOST: $graphitehost, PORT: $graphiteport \n";`

**Comment by ToMo999** [comment]
your right. the var "graphite_host" isn't loaded correctly. 
I see "127.0.0.1". when I change the default in fos2graphite.pl to 1.1.2.2 it's worked. And I see the first data in graphite. 
So the vars for the seed-switch will be loaded correctly. 
I double-checked the line with the graphite_host in the conf. but no space or typo in there...

**Comment by mamoep** [comment]
We'll check the code and come back to you!

**Comment by mamoep** [comment]
I found the bug and committed a fix to master branch. See commit https://github.com/openiomon/fos2graphite/commit/763c9159b6fd755a7723fce1eb9128afbb7ffd60

**Comment by mamoep** [comment]
Release 0.4.1 with the fix is now available
